# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/physical.xdc

# Block Designs: bd/physical_bd/physical_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==physical_bd || ORIG_REF_NAME==physical_bd} -quiet] -quiet

# IP: bd/physical_bd/ip/physical_bd_processing_system7_0_0/physical_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==physical_bd_processing_system7_0_0 || ORIG_REF_NAME==physical_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/physical_bd/ip/physical_bd_axi_gpio_0_0/physical_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==physical_bd_axi_gpio_0_0 || ORIG_REF_NAME==physical_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/physical_bd/ip/physical_bd_ps7_0_axi_periph_0/physical_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==physical_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==physical_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/physical_bd/ip/physical_bd_rst_ps7_0_50M_0/physical_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==physical_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==physical_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/physical_bd/ip/physical_bd_LED_CTR_0_0/physical_bd_LED_CTR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==physical_bd_LED_CTR_0_0 || ORIG_REF_NAME==physical_bd_LED_CTR_0_0} -quiet] -quiet

# IP: bd/physical_bd/ip/physical_bd_auto_pc_0/physical_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==physical_bd_auto_pc_0 || ORIG_REF_NAME==physical_bd_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Nizamettin/Documents/GitHub/VIVADO_Z7020_PS_UART_PL_LED/project_1/project_1.gen/sources_1/bd/physical_bd/physical_bd_ooc.xdc
